this.Urls=(function(){var Urls={};var self={url_patterns:{}};var _get_url=function(url_pattern){return function(){var _arguments,index,url,url_arg,url_args,_i,_len,_ref,_ref_list,match_ref,provided_keys,build_kwargs;_arguments=arguments;_ref_list=self.url_patterns[url_pattern];if(arguments.length==1&&typeof(arguments[0])=="object"){var provided_keys_list=Object.keys(arguments[0]);provided_keys={};for(_i=0;_i<provided_keys_list.length;_i++)
provided_keys[provided_keys_list[_i]]=1;match_ref=function(ref)
{var _i;if(ref[1].length!=provided_keys_list.length)
return false;for(_i=0;_i<ref[1].length&&ref[1][_i]in provided_keys;_i++);return _i==ref[1].length;}
build_kwargs=function(keys){return _arguments[0];}}else{match_ref=function(ref)
{return ref[1].length==_arguments.length;}
build_kwargs=function(keys){var kwargs={};for(var i=0;i<keys.length;i++){kwargs[keys[i]]=_arguments[i];}
return kwargs;}}
for(_i=0;_i<_ref_list.length&&!match_ref(_ref_list[_i]);_i++);if(_i==_ref_list.length)
return null;_ref=_ref_list[_i];url=_ref[0],url_args=build_kwargs(_ref[1]);for(url_arg in url_args){var url_arg_value=url_args[url_arg];if(url_arg_value===undefined||url_arg_value===null){url_arg_value='';}else{url_arg_value=url_arg_value.toString();}
url=url.replace("%("+url_arg+")s",url_arg_value);}
return'/'+url;};};var name,pattern,url,url_patterns,_i,_len,_ref;url_patterns=[['ajax:auth_login',[['en\u002Dus/ajax/login\u002Dajax/',[]]],],['ajax:create_city',[['en\u002Dus/ajax/ajax/create\u002Dcity/',[]]],],['lesson:action',[['en\u002Dus/lesson/book/%(pk)s/action/%(action)s/',['pk','action',]]],],['lesson:book',[['en\u002Dus/lesson/book/%(pk)s/',['pk',]]],],['lesson:calendar',[['en\u002Dus/lesson/calendar/',[]]],],['lesson:detail',[['en\u002Dus/lesson/%(pk)s/',['pk',]]],],['lesson:feedback',[['en\u002Dus/lesson/feedback/',[]]],],['lesson:free_time',[['en\u002Dus/lesson/book/%(pk)s/free\u002Dtime/',['pk',]]],],['lesson:list',[['en\u002Dus/lesson/',[]]],],['lesson:make_proposal',[['en\u002Dus/lesson/book/%(pk)s/action/make\u002Dproposal/',['pk',]]],],['social_users:ajax_message',[['en\u002Dus/users/ajax/message/',[]]],],['social_users:ajax_notify_item',[['en\u002Dus/users/ajax/notify/item/',[]]],],['social_users:ajax_notify_read',[['en\u002Dus/users/ajax/notify/read/',[]]],],['social_users:block',[['en\u002Dus/users/block/%(pk)s/',['pk',]]],],['social_users:dialog',[['en\u002Dus/users/dialogs/%(pk)s/',['pk',]]],],['social_users:dialogs',[['en\u002Dus/users/dialogs/',[]]],],['social_users:friends',[['en\u002Dus/users/friends/%(tp)s/',['tp',]]],],['social_users:subscribe',[['en\u002Dus/users/friends/subscribe/%(pk)s/',['pk',]]],],['social_users:unblock',[['en\u002Dus/users/unblock/%(pk)s/',['pk',]]],],['social_users:unfollow',[['en\u002Dus/users/friends/unfollow/%(pk)s/',['pk',]]],],['social_utils:rating',[['en\u002Dus/social\u002Dutils/rating/',[]]],],['video:detail',[['en\u002Dus/video/%(category)s/%(slug)s/',['category','slug',]]],],['video:get_translate',[['en\u002Dus/video/get\u002Dtranslate/',[]]],],['video:list',[['en\u002Dus/video/%(category)s/',['category',]]],],['video:series_video',[['en\u002Dus/video/series/%(pk)s/',['pk',]]]]];self.url_patterns={};for(_i=0,_len=url_patterns.length;_i<_len;_i++){_ref=url_patterns[_i],name=_ref[0],pattern=_ref[1];self.url_patterns[name]=pattern;url=_get_url(name);Urls[name]=url;Urls[name.replace(/-/g,'_')]=url;}
return Urls;})();